objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Prospect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prospect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Prospect__c</fullName>
        <label>Relationship to Prospect</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Created_From_Opportunity_Action__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Relationship_to_Prospect</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Family Member/Influencer/Household Member of Prospect</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Occupancy__c.object
<CustomObject>
    <label>Occupancy</label>
    <nameField>
        <label>Occupancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Occupancies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <formula>TEXT(Source_Opportunity__r.Community__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Occupancy_Tab_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Occupancy Tab Setting</label>
    <fields>
        <fullName>Enable_Reset_Deposit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Reset Deposit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Remove_Prospect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Remove Prospect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Reverse_Move_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Reverse Move-Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reset_Deposit_User_Names__c</fullName>
        <label>Reset Deposit User Names</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Remove_Prospect_User_Names__c</fullName>
        <label>Remove Prospect User Names</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Add_Missing_Resident__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Add Missing Resident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reverse_Move_Out_User_Names__c</fullName>
        <label>Reverse Move-Out User Names</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Add_Temporary_SNF_Stay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Add Temporary SNF Stay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Add_Missing_Resident_User_Names__c</fullName>
        <label>Add Missing Resident User Names</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Add_Temporary_SNF_Stay_User_Names__c</fullName>
        <label>Add Temporary SNF Stay User Names</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Add_Temporary_Respite_Stay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Add Temporary Respite Stay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Add_Temporary_Respite_Stay_User_Names__c</fullName>
        <label>Add Temporary Respite Stay User Names</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Apartment</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>if (
(TEXT(StageName ) = &apos;New&apos; || TEXT(StageName ) = &apos;Pending Qualification&apos; || TEXT(StageName ) = &apos;Visit&apos; )
&amp;&amp;
NOT(ISBLANK( TEXT(Lead_Score__c) ))
, TEXT(Lead_Score__c), TEXT(StageName ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Housing_Type__c</fullName>
        <label>Level of Care</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Independent Living</fullName>
                </value>
                <value>
                    <fullName>Assisted Living</fullName>
                </value>
                <value>
                    <fullName>Memory Care</fullName>
                </value>
                <value>
                    <fullName>Skilled Nursing</fullName>
                </value>
                <value>
                    <fullName>Active Adult</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>50% ROC</fullName>
                </value>
                <value>
                    <fullName>90% ROC</fullName>
                </value>
                <value>
                    <fullName>ROC I</fullName>
                </value>
                <value>
                    <fullName>ROC II</fullName>
                </value>
                <value>
                    <fullName>Unbundled</fullName>
                </value>
                <value>
                    <fullName>75% ROC</fullName>
                </value>
                <value>
                    <fullName>Type A Traditional</fullName>
                </value>
                <value>
                    <fullName>Type A 90% ROC</fullName>
                </value>
                <value>
                    <fullName>Type A 50% ROC</fullName>
                </value>
                <value>
                    <fullName>Type B 90% ROC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Resident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Resident</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Second Resident)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Resident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Resident</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Resident)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Move_In_Date__c</fullName>
        <label>Expected Move In Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Unit__c.object
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Occupied</fullName>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Floor_Plan__c</fullName>
        <label>Floor Plan</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Id__c</fullName>
        <label>Community</label>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Apartments</relationshipLabel>
        <relationshipName>Apartments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing_Type__c</fullName>
        <label>Housing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Housing_Type</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Primary_Community__c</fullName>
        <label>Primary Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Community_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>APT</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>BAK</fullName>
    </customValue>
    <customValue>
        <fullName>CAB</fullName>
    </customValue>
    <customValue>
        <fullName>DTT</fullName>
    </customValue>
    <customValue>
        <fullName>EAA</fullName>
    </customValue>
    <customValue>
        <fullName>GDD</fullName>
    </customValue>
    <customValue>
        <fullName>Lutheran Home</fullName>
    </customValue>
    <customValue>
        <fullName>Birdwood</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
        <isActive>false</isActive>
        <label>TEST</label>
    </customValue>
    <masterLabel>Community Picklist</masterLabel>
</GlobalValueSet>

globalValueSets/Housing_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Assisted Living</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Living</fullName>
        <default>true</default>
        <label>Independent Living</label>
    </customValue>
    <customValue>
        <fullName>Residential Living</fullName>
    </customValue>
    <customValue>
        <fullName>Assisted Living Respite</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Day Club</fullName>
    </customValue>
    <customValue>
        <fullName>Assisted Living Memory Support</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Respite</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Rehab</fullName>
    </customValue>
    <customValue>
        <fullName>Memory Support</fullName>
    </customValue>
    <customValue>
        <fullName>Hospice</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>Skilled Nursing</fullName>
    </customValue>
    <customValue>
        <fullName>Community Events</fullName>
        <isActive>false</isActive>
        <label>Community Events</label>
    </customValue>
    <customValue>
        <fullName>Memory Care</fullName>
        <isActive>false</isActive>
        <label>Memory Care</label>
    </customValue>
    <masterLabel>Housing Type</masterLabel>
</GlobalValueSet>

globalValueSets/Relationship_to_Prospect.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Self</fullName>
    </customValue>
    <customValue>
        <fullName>Friend</fullName>
    </customValue>
    <customValue>
        <fullName>Spouse</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Son</fullName>
    </customValue>
    <customValue>
        <fullName>Daughter</fullName>
    </customValue>
    <customValue>
        <fullName>Sister</fullName>
    </customValue>
    <customValue>
        <fullName>Brother</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Other Relative</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Guardian</fullName>
    </customValue>
    <masterLabel>Relationship to Prospect</masterLabel>
</GlobalValueSet>

classes/ManageOccupancyControllerTest.cls
@isTest
public class ManageOccupancyControllerTest {

    @isTest
	static void myUnitTest01(){
        string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
        
		string strPriComm = strCOMM1;
		//for (User oUser : [SELECT Id, Primary_Community__c FROM User WHERE Id = :UserInfo.getUserId() AND Primary_Community__c != null])
		//	strPriComm = oUser.Primary_Community__c;
		List<Opportunity> oList = new List<Opportunity>();

		Account acc = new Account();
		acc.Name = 'WICB';
		Account acc1 = new Account();
		acc1.Name = 'SLCB';
		insert new list<Account>{acc1,acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c3 = new Contact(FirstName = 'E', LastName = 'F', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
        
        Contact ci = new Contact(FirstName = 'A1', LastName = 'B1', AccountId = acc1.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2i = new Contact(FirstName = 'C1', LastName = 'D1',  AccountId = acc1.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c3i = new Contact(FirstName = 'E1', LastName = 'F1', AccountId = acc1.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
        
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		cList.add(c3);
        cList.add(ci);
		cList.add(c2i);
		cList.add(c3i);
		Insert cList;
		
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id); //,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		insert u1;

		Opportunity opp = new Opportunity(Primary_Resident__c=c.Id, Second_Resident__c=c2.Id);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		opp.Move_In_Date__c = Date.Today().AddDays(-20);
		
		oList.add(opp);
		
		Opportunity opp1 = new Opportunity();
		opp1.Name = 'Steve Smith';
		opp1.AccountId = acc1.Id;
		opp1.CloseDate = Date.Today();
		opp1.StageName = 'Prospecting';
		opp1.Unit__c = u.id;
		opp1.Move_In_Date__c = Date.Today().AddDays(-1);
		oList.add(opp1);

		Opportunity opp2 = new Opportunity();
		opp2.Name = 'Steve Smith';
		opp2.AccountId = acc1.Id;
		opp2.CloseDate = Date.Today().AddDays(50);
		opp2.StageName = 'Prospecting';
		opp2.Unit__c = u1.id;
		opp2.Move_In_Date__c = Date.Today().AddDays(50);
		oList.add(opp2);
		test.startTest();
		insert oList;
		test.stopTest();
		delete oList;
	}
    
    @isTest
	static void myUnitTest04(){
        string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		//for (User oUser : [SELECT Id, Primary_Community__c FROM User WHERE Id = :UserInfo.getUserId() AND Primary_Community__c != null])
		//	strPriComm = oUser.Primary_Community__c;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm,Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm,Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		opp.Move_In_Date__c = Date.Today().AddDays(-20);
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.GetApartments(strPriComm,strResidentialLiving,u1.Id,opp.Id,true);
		test.stopTest();
		
	}
    
    @isTest
	static void myUnitTest05(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.MoveOut(opp.Id, 'Move-Out', string.valueOf(Date.Today().AddDays(-2)), 'Test', c.Id, c2.Id, '');
		test.stopTest();
		
	}
    
    @isTest
	static void myUnitTest06(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id,Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.GetTransferFormParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.Transfer(opp.Id, 'Transfer', string.valueOf(Date.Today().AddDays(-2)), strResidentialLiving, u1.Id, c.Id, null, '','');
		//ManageOccupancyController.GetRebatableRefundParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.MoveOut(opp.Id, 'Move-Out', string.valueOf(Date.Today().AddDays(-2)), 'Test', null, c2.Id, '100');
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest07(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id,Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.GetTransferFormParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.Transfer(opp.Id, 'Schedule Transfer', string.valueOf(Date.Today().AddDays(-2)), strResidentialLiving, u1.Id, c.Id, null, '','100');
		//ManageOccupancyController.GetRebatableRefundParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.MoveOut(opp.Id, 'Schedule Move-Out', string.valueOf(Date.Today().AddDays(-2)), 'Test', null, c2.Id, '100');
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest08(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id,Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.GetTransferFormParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.Transfer(opp.Id, 'Schedule Transfer', string.valueOf(Date.Today().AddDays(2)), strResidentialLiving, u1.Id, c.Id, null, '','');
		//ManageOccupancyController.GetRebatableRefundParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.MoveOut(opp.Id, 'Schedule Move-Out', string.valueOf(Date.Today().AddDays(2)), 'Test', null, c2.Id, '100');
		test.stopTest();
		ManageOccupancyController.GetPendingChanges(opp.Id);
	}
    
    @isTest
	static void myUnitTest09(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id,Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(1)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.GetTransferFormParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.Transfer(opp.Id, 'Schedule Transfer', string.valueOf(Date.Today().AddDays(2)), strResidentialLiving, u1.Id, c.Id, null, '100','');
		//ManageOccupancyController.GetRebatableRefundParams(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.MoveOut(opp.Id, 'Schedule Move-Out', string.valueOf(Date.Today().AddDays(2)), 'Test', null, c2.Id, '100');
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest10(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.GetTransferFormParams(opp.Id);
		OccTrigHelper.CalledOppTriggerOnce=false;
		opp.Primary_Resident__c=c2.Id;
		update opp;
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		//ManageOccupancyController.Transfer(opp.Id, 'Transfer', string.valueOf(Date.Today().AddDays(-2)), strResidentialLiving, u1.Id, c.Id, null, '');
		//ManageOccupancyController.GetRebatableRefundParams(opp.Id);
		//OccTrigHelper.CalledOppTriggerOnce=false;
		//ManageOccupancyController.MoveOut(opp.Id, 'Move-Out', string.valueOf(Date.Today().AddDays(-2)), 'Test', null, c2.Id, '100');
		test.stopTest();
		
		
	}
    
    @isTest
	static void myUnitTest11(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		//ManageOccupancyController.PayPromissoryNote(opp.Id, null, string.valueOf(Date.Today().AddDays(-1)));
		//ManageOccupancyController.PayPromissoryNote(opp.Id, 1000, null);
		//ManageOccupancyController.PayPromissoryNote(opp.Id, 1000, string.valueOf(Date.Today().AddDays(-1)));
		test.stopTest();
		
		
	}
    
    @isTest
	static void myUnitTest12(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id,Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(1)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.Transfer(opp.Id, 'Schedule Transfer', string.valueOf(Date.Today().AddDays(2)), strResidentialLiving, u1.Id, c.Id, null, '100','');
		ManageOccupancyController.GetCancelScheduledTransferFormParams(opp.Id);
		ManageOccupancyController.CancelScheduledTransfer(opp.Id, c.Id, null);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.MoveOut(opp.Id, 'Schedule Move-Out', string.valueOf(Date.Today().AddDays(2)), 'Test', null, c2.Id, '100');
		ManageOccupancyController.GetCancelScheduledMoveOutFormParams(opp.Id);
		ManageOccupancyController.CancelScheduledMoveOut(opp.Id, null, c2.Id);
		//ManageOccupancyController.GetPromissoryNoteDueAmt(opp.Id);
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest12a(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id, Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id,Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(1)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.Transfer(opp.Id, 'Schedule Transfer', string.valueOf(Date.Today().AddDays(2)), strResidentialLiving, u1.Id, c.Id, null, '100','');
		ManageOccupancyController.GetCancelScheduledTransferFormParams(opp.Id);
		ManageOccupancyController.CancelScheduledTransfer(opp.Id, c.Id, null);
		OccTrigHelper.CalledOppTriggerOnce=false;
		ManageOccupancyController.MoveOut(opp.Id, 'Schedule Move-Out', string.valueOf(Date.Today().AddDays(2)), 'Test', c.Id, null, '100');
		ManageOccupancyController.GetCancelScheduledMoveOutFormParams(opp.Id);
		ManageOccupancyController.CancelScheduledMoveOut(opp.Id, c.Id, null);
		//ManageOccupancyController.GetPromissoryNoteDueAmt(opp.Id);
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest13(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
        opp.Expected_Move_In_Date__c=date.today().addDays(5);
        update opp;
        
        Occupancy_Tab_Setting__c ots = new Occupancy_Tab_Setting__c(Enable_Reset_Deposit__c=true,Enable_Remove_Prospect__c=true, Enable_Add_Missing_Resident__c=true, Reset_Deposit_User_Names__c=UserInfo.getUserName(), Add_Missing_Resident_User_Names__c=UserInfo.getUserName(), Remove_Prospect_User_Names__c=UserInfo.getUserName(),Enable_Reverse_Move_Out__c=true, Enable_Add_Temporary_Respite_Stay__c=true, Enable_Add_Temporary_SNF_Stay__c=true);
		insert ots;
		
		test.startTest();
		ManageOccupancyController.GetAddSecondResidentFormParams(opp.Id);
        ManageOccupancyController.AddSecondResident(opp.Id,c2.Id,datetime.newInstance(date.today().year(),date.today().month(),date.today().day()).format('yyyy-MM-dd'),strResidentialLiving,u.Id,true);
        ManageOccupancyController.GetPendingChanges(opp.Id);
        ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetRemoveProspectFormParams(opp.Id);
        ManageOccupancyController.RemoveProspect(opp.Id, c.Id);
        ManageOccupancyController.OccupancyTabSetting  cs = new ManageOccupancyController.OccupancyTabSetting();
		//ManageOccupancyController.GetPromissoryNoteDueAmt(opp.Id);
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest14(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
        Contact c3 = new Contact(FirstName = 'E', LastName = 'F',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
        cList.add(c3);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
        Occupancy_Tab_Setting__c ots = new Occupancy_Tab_Setting__c(Enable_Remove_Prospect__c=true, Enable_Add_Missing_Resident__c=true, Enable_Reset_Deposit__c=true, Add_Missing_Resident_User_Names__c=null, Remove_Prospect_User_Names__c=null);
		insert ots;
		
		oList.add(opp);

		insert oList;
		
		test.startTest();
        ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today()),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
        ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetAddSecondResidentFormParams(opp.Id);
        ManageOccupancyController.AddSecondResident(opp.Id,c2.Id,datetime.newInstance(date.today().year(),date.today().month(),date.today().day()).format('yyyy-MM-dd'),strResidentialLiving,u.Id,false);
		test.stopTest();
	}
    
    
    @isTest
	static void myUnitTest15(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
        Contact c3 = new Contact(FirstName = 'E', LastName = 'F',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
        cList.add(c3);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
        Occupancy_Tab_Setting__c ots = new Occupancy_Tab_Setting__c(Enable_Remove_Prospect__c=true, Enable_Add_Missing_Resident__c=true, Add_Missing_Resident_User_Names__c=null, Remove_Prospect_User_Names__c=null);
		insert ots;
		
		oList.add(opp);

		insert oList;
		////CancelDeposit(Id OppId, string strCancelDate, string strCancelReason, string strRefundAmount, string strCompetitor, boolean SetAccountStatustoLost ){
		test.startTest();
        //ManageOccupancyController.GetCancelDepositFormParams(opp.Id);
        //////ManageOccupancyController.AddSecondResident(opp.Id,c2.Id,datetime.newInstance(date.today().year(),date.today().month(),date.today().day()).format('yyyy-MM-dd'),strResidentialLiving,u.Id,false);
        //ManageOccupancyController.CancelDeposit(opp.Id, datetime.newInstance(date.today().year(),date.today().month(),date.today().day()).format('yyyy-MM-dd'), 'Death', '100', null,'',true );
		test.stopTest();
	}
    
    @isTest
	static void myUnitTest16(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
        Contact c3 = new Contact(FirstName = 'E', LastName = 'F',  AccountId = acc.Id,Prospect__c=true,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
        cList.add(c3);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Contract_Type__c='Rebatable 50%',Amount=1000);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Depositor';
		opp.Unit__c = u.id;
        Occupancy_Tab_Setting__c ots = new Occupancy_Tab_Setting__c(Enable_Remove_Prospect__c=true, Enable_Add_Missing_Resident__c=true, Enable_Reset_Deposit__c=true, Add_Missing_Resident_User_Names__c=null, Remove_Prospect_User_Names__c=null);
		insert ots;
		
		oList.add(opp);

		insert oList;
		////CancelDeposit(Id OppId, string strCancelDate, string strCancelReason, string strRefundAmount, string strCompetitor, boolean SetAccountStatustoLost ){
		test.startTest();
        ManageOccupancyController.GetButtonNames(opp.Id);
        //ManageOccupancyController.GetCancelDepositFormParams(opp.Id);
        ////ManageOccupancyController.AddSecondResident(opp.Id,c2.Id,datetime.newInstance(date.today().year(),date.today().month(),date.today().day()).format('yyyy-MM-dd'),strResidentialLiving,u.Id,false);
        //ManageOccupancyController.ResetDeposit(opp.Id);
		test.stopTest();
	}
	
	@isTest
	static void myUnitTest17(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;
		Id redTypeId = ([SELECT Id, name, DeveloperName FROM RecordType where SObjectType = 'Opportunity' and name = 'Senior Living' limit 1]).Id;
		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		opp.RecordTypeId=redTypeId;
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		ManageOccupancyController.GetMoveOutFormParams(opp.Id);
		ManageOccupancyController.MoveOut(opp.Id, 'Move-Out', string.valueOf(Date.Today().AddDays(-2)), 'Test', c.Id, c2.Id, '');
        Occupancy_Tab_Setting__c ots = new Occupancy_Tab_Setting__c(Enable_Reverse_Move_Out__c=true, Enable_Reset_Deposit__c=true,Enable_Remove_Prospect__c=true, Enable_Add_Missing_Resident__c=true, Reset_Deposit_User_Names__c=UserInfo.getUserName(), Add_Missing_Resident_User_Names__c=UserInfo.getUserName(), Remove_Prospect_User_Names__c=UserInfo.getUserName(), Reverse_Move_Out_User_Names__c=UserInfo.getUserName(),Enable_Add_Temporary_Respite_Stay__c=true, Enable_Add_Temporary_SNF_Stay__c=true,Add_Temporary_Respite_Stay_User_Names__c=UserInfo.getUserName(),Add_Temporary_SNF_Stay_User_Names__c=UserInfo.getUserName());
		insert ots;
        ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetReverseMoveOutFormParams(opp.Id);
		ManageOccupancyController.ReverseMoveOut(opp.Id, c.Id, c2.Id);
		test.stopTest();
		
	}
    
    @isTest
	static void myUnitTest17aa(){
		string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm, Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		
		oList.add(opp);

		insert oList;
		
		
		test.startTest();
		ManageOccupancyController.MoveIn(opp.Id,'Regular',string.valueOf(Date.Today().AddDays(-20)),u.Id,'100.00',string.valueOf(Date.Today().AddDays(-21)),'100','Yes');
		test.stopTest();
        OccTrigHelper.CalledOppTriggerOnce = false;
        list<occupancy__c> lstOccUv = new list<occupancy__c>();
        for (occupancy__c oocc : [SELECT Id, Move_In_Date__c FROM occupancy__c where Move_In_Date__c !=null]){
        oocc.Move_In_Date__c = oocc.Move_In_Date__c-1;
        lstOccUv.add(oocc);
        }
        update lstOccUv;
		
	}
    
    @isTest
	static void myUnitTest18(){
        string strCOMM1 = '';
        for(Schema.PicklistEntry f : Opportunity.Community__c.getDescribe().getPicklistValues()) if (f.getValue().length()>3){
            strCOMM1 = f.getValue();
            break;
        }
        Community__c ocomm = new Community__c(Name=strCOMM1);
        insert ocomm;
        //Floor_Plan__c fp = new Floor_Plan__c(Community_Id__c = ocomm.Id, Name='FP01',Community__c=strCOMM1,Floor_Plan_Type__c='FP Type');
        //insert fp;
		string strPriComm = strCOMM1;
		//for (User oUser : [SELECT Id, Primary_Community__c FROM User WHERE Id = :UserInfo.getUserId() AND Primary_Community__c != null])
		//	strPriComm = oUser.Primary_Community__c;
		List<Opportunity> oList = new List<Opportunity>();
		
		Account acc = new Account();
		acc.Name = 'WICB';
		insert new list<Account>{acc};
			
		Contact c = new Contact(FirstName = 'A', LastName = 'B', AccountId = acc.Id,Relationship_to_Prospect__c='Self');
		Contact c2 = new Contact(FirstName = 'C', LastName = 'D',  AccountId = acc.Id,Relationship_to_Prospect__c='Self');
		
		List<Contact> cList = new List<Contact>();
		cList.add(c);
		cList.add(c2);
		Insert cList;
		final string strResidentialLiving = 'Residential Living';
		Unit__c u = new Unit__c(Community__c = strPriComm,Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u.Name = 'Unit001';
		u.Status__c = 'Vacant';
		u.Housing_Type__c=strResidentialLiving;
		insert u;
		
		Unit__c u1 = new Unit__c(Community__c = strPriComm,Community_Id__c=ocomm.Id);//,Floor_Plan_Id__c=fp.Id
		u1.Name = 'Unit002';
		u1.Status__c = 'Vacant';
		u1.Housing_Type__c=strResidentialLiving;
		insert u1;

		Opportunity opp = new Opportunity(Community__c = strPriComm,Primary_Resident__c=c.Id, Second_Resident__c=c2.Id);
		opp.Name = 'Viv Richards';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.Today();
		opp.StageName = 'Prospecting';
		opp.Unit__c = u.id;
		opp.Move_In_Date__c = Date.Today().AddDays(-20);
		
		oList.add(opp);

		insert oList;
		
		Occupancy_Tab_Setting__c ots = new Occupancy_Tab_Setting__c(Enable_Reverse_Move_Out__c=true, Enable_Reset_Deposit__c=true,Enable_Remove_Prospect__c=true, Enable_Add_Missing_Resident__c=true, Reset_Deposit_User_Names__c=UserInfo.getUserName(), Add_Missing_Resident_User_Names__c=UserInfo.getUserName(), Remove_Prospect_User_Names__c=UserInfo.getUserName(), Reverse_Move_Out_User_Names__c=UserInfo.getUserName(),Enable_Add_Temporary_Respite_Stay__c=true, Enable_Add_Temporary_SNF_Stay__c=true,Add_Temporary_Respite_Stay_User_Names__c=UserInfo.getUserName(),Add_Temporary_SNF_Stay_User_Names__c=UserInfo.getUserName());
		insert ots;
		test.startTest();
		ManageOccupancyController.GetOccupancies(opp.Id);
		ManageOccupancyController.GetPendingChanges(opp.Id);
		ManageOccupancyController.GetButtonNames(opp.Id);
		ManageOccupancyController.GetMoveInFormParams(opp.Id,'Regular');
		ManageOccupancyController.GetApartments(strPriComm,strResidentialLiving,u1.Id,opp.Id,true);
		test.stopTest();
		
	}

}