objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Inquiry_Date__c</fullName>
        <label>Inquiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Source Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Relationship_to_Prospect__c</fullName>
        <label>Relationship to Prospect</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Created_From_Opportunity_Action__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Relationship_to_Prospect</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Family Member/Influencer/Household Member of Prospect</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Inquiry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Inquiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Merge_to_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merge to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Merge to Contact)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect_Last_Name__c</fullName>
        <label>Prospect Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Source Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Activity_Type__c</fullName>
        <label>Initial Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Call In</fullName>
                </value>
                <value>
                    <fullName>Initial Email In</fullName>
                </value>
                <value>
                    <fullName>Initial Mail In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In Appointment</fullName>
                </value>
                <value>
                    <fullName>Initial Call Out</fullName>
                </value>
                <value>
                    <fullName>Initial Email Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Addl_Prospect_Last_Name__c</fullName>
        <label>Addl Prospect Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Activity_Date__c</fullName>
        <label>Follow Up Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Activity_Type__c</fullName>
        <label>Follow Up Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Call In</fullName>
                </value>
                <value>
                    <fullName>Call Out</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Closing Appointment</fullName>
                </value>
                <value>
                    <fullName>Community Experience</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>Email In</fullName>
                </value>
                <value>
                    <fullName>Email Out</fullName>
                </value>
                <value>
                    <fullName>Home Visit</fullName>
                </value>
                <value>
                    <fullName>Initial Appointment</fullName>
                </value>
                <value>
                    <fullName>Initial Call In</fullName>
                </value>
                <value>
                    <fullName>Initial Email In</fullName>
                </value>
                <value>
                    <fullName>Initial Mail In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In Appointment</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Mail In</fullName>
                </value>
                <value>
                    <fullName>Mail Out - Personal Mail</fullName>
                </value>
                <value>
                    <fullName>Move In</fullName>
                </value>
                <value>
                    <fullName>Move Out</fullName>
                </value>
                <value>
                    <fullName>Post-Deposit Appointment</fullName>
                </value>
                <value>
                    <fullName>Resident Appointment</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_to_Prospect__c</fullName>
        <label>Relationship to Prospect</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship_to_Prospect</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Add_ReInquiry_to_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Add ReInquiry to Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Lead_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

globalValueSets/Relationship_to_Prospect.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Self</fullName>
    </customValue>
    <customValue>
        <fullName>Friend</fullName>
    </customValue>
    <customValue>
        <fullName>Spouse</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Son</fullName>
    </customValue>
    <customValue>
        <fullName>Daughter</fullName>
    </customValue>
    <customValue>
        <fullName>Sister</fullName>
    </customValue>
    <customValue>
        <fullName>Brother</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Other Relative</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Guardian</fullName>
    </customValue>
    <masterLabel>Relationship to Prospect</masterLabel>
</GlobalValueSet>

classes/AutoConvertLeadsTest.cls
@isTest
public class AutoConvertLeadsTest {

    public static testMethod void AutoConvertLeadsTest () {
    
        Campaign  c = new Campaign(IsActive = true, Name = 'Test');
        insert c;
    
        Lead ld = new Lead();
        ld.FirstName = 'Test';
        ld.LastName = 'Test';
        ld.Company = 'Test Test';
        //ld.Relationship_to_Prospect__c = 'Self';
        ld.Lead_Source_Campaign__c = c.id;
        ld.Follow_Up_Activity_Type__c = 'Call Out';
        ld.Follow_Up_Activity_Date__c = Date.today();
        ld.Initial_Activity_Type__c = 'Call Out';
        ld.LeadSource = 'Other';
        ld.Prospect_Last_Name__c = 'Test3';
        ld.Addl_Prospect_Last_Name__c = 'Test2';
        //ld.Addl_Relationship_to_Prospect__c  = 'Spouse';
        ld.Inquiry_Date__c = Date.TODAY();
        
        insert ld;
        
        List<Id> lstIds = new List<Id>();
        lstIds.add(ld.Id);
        
        AutoConvertLeads.LeadAssign(lstIds );

      
    }
    
     public static testMethod void AutoConvertLeadsMergeTest () {

      String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String hhRecordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Household').getRecordTypeId();
        String rcrecordTypeId  = Schema.getGlobalDescribe().get('HealthCloudGA__ReciprocalRole__c').getDescribe().getRecordTypeInfosByName().get('Contact Role').getRecordTypeId();
        List<Opportunity> oList = new List<Opportunity>();
        Id pcId;
        
        
        List<Account> alist = new List<Account>();        
        Account hhaobj1 = new Account();
        hhaobj1.Name = 'Test122 Account';
        hhaobj1.RecordTypeID = hhRecordTypeId;
        alist.add(hhaobj1); 
        Account hhaobj2 = new Account();
        hhaobj2.Name = 'Test12233 Account';
        hhaobj2.RecordTypeID = hhRecordTypeId;
        alist.add(hhaobj2); 
               

        Account accPer1 = new Account();
        accPer1.FirstName='Test FName';
        accPer1.LastName='Test LName';
        accPer1.PersonEmail = 'testtesttest1231456789@test.com';
        accPer1.PersonMailingCity = 'Crystal City';
        accPer1.RecordTypeID = recordTypeId;
        alist.add(accPer1);
        Account accPer2 = new Account();
        accPer2.FirstName='Test FName333';
        accPer2.LastName='Test LName333';
        accPer2.RecordTypeID = recordTypeId;
        accPer2.PersonEmail = 'testtesttest123145678@test.com';
        accPer2.PersonHomePhone = '444-444-4949';
        accPer2.PersonMailingCity = 'Arlington';
        alist.add(accPer2);

        insert alist;
        
        Id conId;
        for (Account a : [Select PersonContactId from Account where PersonContactId != null])
            conId = a.PersonContactId;
        
        List<AccountContactRelation> acrList = new List<AccountContactRelation>();
        AccountContactRelation acr1 = new AccountContactRelation(AccountId = hhaobj1.Id, ContactId = conId );
 
        acrList.add(acr1);
     
        insert acrList;
    
        Campaign  c = new Campaign(IsActive = true, Name = 'Test');
        insert c;
    
        Lead ld = new Lead();
        ld.FirstName = 'Test';
        ld.LastName = 'Test';
        ld.Company = 'Test Test';
        // ld.Relationship_to_Prospect__c = 'Self';
        ld.Lead_Source_Campaign__c = c.id;
        ld.Follow_Up_Activity_Type__c = 'Call Out';
        ld.Follow_Up_Activity_Date__c = Date.today();
        ld.Initial_Activity_Type__c = 'Call Out';
        ld.LeadSource = 'Other';
        ld.Prospect_Last_Name__c = 'Test3';
        ld.Addl_Prospect_Last_Name__c = 'Test2';
        //ld.Addl_Relationship_to_Prospect__c  = 'Spouse';
        ld.Inquiry_Date__c = Date.TODAY();
        ld.Merge_to_Contact__c = conId ;
          
        insert ld;
        
        List<Id> lstIds = new List<Id>();
        lstIds.add(ld.Id);
     
        Test.StartTest();
        AutoConvertLeads.LeadAssign(lstIds );
        Test.StopTest();
      
    }
    
     public static testMethod void AutoConvertLeadsMergeTest2 () {
    
      String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String hhRecordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Household').getRecordTypeId();
        String rcrecordTypeId  = Schema.getGlobalDescribe().get('HealthCloudGA__ReciprocalRole__c').getDescribe().getRecordTypeInfosByName().get('Contact Role').getRecordTypeId();
        List<Opportunity> oList = new List<Opportunity>();
        Id pcId;
        
        
        List<Account> alist = new List<Account>();        
        Account hhaobj1 = new Account();
        hhaobj1.Name = 'Test122 Account';
        hhaobj1.RecordTypeID = hhRecordTypeId;
        alist.add(hhaobj1); 
        Account hhaobj2 = new Account();
        hhaobj2.Name = 'Test12233 Account';
        hhaobj2.RecordTypeID = hhRecordTypeId;
        alist.add(hhaobj2); 
               

        Account accPer1 = new Account();
        accPer1.FirstName='Test FName';
        accPer1.LastName='Test LName';
        accPer1.PersonEmail = 'testtesttest1231456789@test.com';
        accPer1.PersonMailingCity = 'Crystal City';
        accPer1.RecordTypeID = recordTypeId;
        alist.add(accPer1);
        Account accPer2 = new Account();
        accPer2.FirstName='Test FName333';
        accPer2.LastName='Test LName333';
        accPer2.RecordTypeID = recordTypeId;
        accPer2.PersonEmail = 'testtesttest123145678@test.com';
        accPer2.PersonHomePhone = '444-444-4949';
        accPer2.PersonMailingCity = 'Arlington';
        alist.add(accPer2);

        insert alist;
        
        Id conId;
        for (Account a : [Select PersonContactId from Account where PersonContactId != null])
            conId = a.PersonContactId;
        
        List<AccountContactRelation> acrList = new List<AccountContactRelation>();
        AccountContactRelation acr1 = new AccountContactRelation(AccountId = hhaobj1.Id, ContactId = conId );
 
        acrList.add(acr1);
     
        insert acrList;
    
        Opportunity o = new Opportunity(StageName = 'Depositor', CloseDate = Date.Today(), Name = 'Test', AccountId = hhaobj1.Id);
        insert o;
    
        Campaign  c = new Campaign(IsActive = true, Name = 'Test');
        insert c;
    
        Lead ld = new Lead();
        ld.Add_ReInquiry_to_Opportunity__c = o.Id;
        
        ld.FirstName = 'Test';
        ld.LastName = 'Test';
        ld.Company = 'Test Test';
        // ld.Relationship_to_Prospect__c = 'Self';
        ld.Lead_Source_Campaign__c = c.id;
        ld.Follow_Up_Activity_Type__c = 'Call Out';
        ld.Follow_Up_Activity_Date__c = Date.today();
        ld.Initial_Activity_Type__c = 'Call Out';
        ld.LeadSource = 'Other';
        ld.Prospect_Last_Name__c = 'Test3';
        ld.Addl_Prospect_Last_Name__c = 'Test2';
        //ld.Addl_Relationship_to_Prospect__c  = 'Spouse';
        ld.Inquiry_Date__c = Date.TODAY();
 
          
        insert ld;
        
        List<Id> lstIds = new List<Id>();
        lstIds.add(ld.Id);
     
        Test.StartTest();
        AutoConvertLeads.LeadAssign(lstIds );
        Test.StopTest();
      
    }
}