objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Score__c</fullName>
        <label>Lead Temperature</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
                <value>
                    <fullName>Cold</fullName>
                </value>
                <value>
                    <fullName>Not Yet Classified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Community_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>APT</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>BAK</fullName>
    </customValue>
    <customValue>
        <fullName>CAB</fullName>
    </customValue>
    <customValue>
        <fullName>DTT</fullName>
    </customValue>
    <customValue>
        <fullName>EAA</fullName>
    </customValue>
    <customValue>
        <fullName>GDD</fullName>
    </customValue>
    <customValue>
        <fullName>Lutheran Home</fullName>
    </customValue>
    <customValue>
        <fullName>Birdwood</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
        <isActive>false</isActive>
        <label>TEST</label>
    </customValue>
    <masterLabel>Community Picklist</masterLabel>
</GlobalValueSet>

classes/MassReassignEvents.cls
public with sharing class MassReassignEvents implements Database.Batchable<sObject>{
    public String assignedTo;
    public String reassignTo;
    public String community;
    public String leadScore;
    public String dateFrom;
    public String dateTo;
    public Boolean includeConsumer;
    public Boolean includeOutreach;

    public MassReassignEvents(String assignedTo, String reassignTo, String community, String leadScore, String dateFrom, String dateTo, Boolean includeConsumer, Boolean includeOutreach) {
        this.assignedTo = assignedTo;
        this.reassignTo = reassignTo;
        this.community = community;
        this.leadScore = leadScore;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.includeConsumer = includeConsumer;
        this.includeOutreach = includeOutreach;
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, WhatId, OwnerId, Account.RecordTypeId FROM Event WHERE Is_Pending__c = True AND OwnerId = :assignedTo';
        Date dateFromObj;
        Date dateToObj;
        if (!string.isBlank(dateFrom) && !string.isBlank(dateTo)) {
            dateFromObj = Date.valueOf(dateFrom);
            dateToObj = Date.valueOf(dateTo);
            query += ' AND ActivityDate >= :dateFromObj AND ActivityDate <= :dateToObj';
        }
        
        return Database.getQueryLocator(query+' ALL ROWS');
     }
  
     public void execute(Database.BatchableContext BC, List<Event> EventList){
        List<Event> EventsToReassign = new List<Event>();
        Map<Id, List<Event>> oppIdToEventsMap = new Map<Id, List<Event>>();

        Id BusinessAccountTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        for(Event event: EventList){
            if (includeConsumer){
                if (event.WhatId.getSObjectType().getDescribe().getName().equals('Opportunity')){
                    if (!oppIdToEventsMap.containsKey(event.WhatId)){
                        List<Event> el = new List<Event>();
                        el.add(event);
                        oppIdToEventsMap.put(event.WhatId, el);
                    } else {
                        oppIdToEventsMap.get(event.WhatId).add(event);
                    }
                }
            }
            if (includeOutreach)
                if (event.Account.RecordTypeId == BusinessAccountTypeId){
                    event.ownerId = reassignTo;
                    eventsToReassign.add(event);
                }
        }

        for(Opportunity opp: [SELECT Id, Community__c, Lead_Score__c FROM Opportunity WHERE Id IN :oppIdToEventsMap.keySet()])
            if ((leadScore.equalsIgnoreCase('All')) || (opp.Lead_Score__c != null && opp.Lead_Score__c.equalsIgnoreCase(leadScore)))
                if ((community.equalsIgnoreCase('All Communities')) || (opp.Community__c != null && opp.Community__c == community))
                    for (Event e: oppIdToEventsMap.get(opp.Id)){
                        e.ownerId = reassignTo;
                        eventsToReassign.add(e);
                    }              
        

        if (eventsToReassign.size() > 0){
            update eventsToReassign;
        }
    }

    public void finish(Database.BatchableContext BC){
    }
}