objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reporting_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Community</label>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Activity.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>System__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Complete__c</fullName>
        <formula>NOT(if (ISBLANK(TEXT(Result_Code__c)), If ( IsTask , if (ISPICKVAL(Status, &apos;Completed&apos;), false, true), true ), false))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Sales Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Call In</fullName>
                </value>
                <value>
                    <fullName>Call Out</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Closing Tour</fullName>
                </value>
                <value>
                    <fullName>Community Experience</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>EBD Call In</fullName>
                </value>
                <value>
                    <fullName>EBD Call Out</fullName>
                </value>
                <value>
                    <fullName>EBD Presentation</fullName>
                </value>
                <value>
                    <fullName>EBD Tour</fullName>
                </value>
                <value>
                    <fullName>Email In</fullName>
                </value>
                <value>
                    <fullName>Email Out</fullName>
                </value>
                <value>
                    <fullName>Home Visit</fullName>
                </value>
                <value>
                    <fullName>Initial Call In</fullName>
                </value>
                <value>
                    <fullName>Initial Email In</fullName>
                </value>
                <value>
                    <fullName>Initial Mail In</fullName>
                </value>
                <value>
                    <fullName>Initial Tour</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In Tour</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Mail In</fullName>
                </value>
                <value>
                    <fullName>MAIL OUT-COMMUNITY NEWSLETTER</fullName>
                </value>
                <value>
                    <fullName>Mail Out - Personal Mail</fullName>
                </value>
                <value>
                    <fullName>Move In</fullName>
                </value>
                <value>
                    <fullName>Move Out</fullName>
                </value>
                <value>
                    <fullName>Post-Deposit Tour</fullName>
                </value>
                <value>
                    <fullName>Resident Tour</fullName>
                </value>
                <value>
                    <fullName>Tour</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Complete_Date__c</fullName>
        <label>Activity Complete Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Family Member/Influencer/Household Member of Prospect</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Referral_Reporting__c.object
<CustomObject>
    <label>Referral Reporting</label>
    <nameField>
        <displayFormat>RR-{0}</displayFormat>
        <label>Referral Reporting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Reporting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Referral Reporting</relationshipLabel>
        <relationshipName>Referral_Reporting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Metric_Type__c</fullName>
        <label>Metric Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing Activity</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Admit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referral Reporting</relationshipLabel>
        <relationshipName>Referral_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referral Reporting (Referral Contact)</relationshipLabel>
        <relationshipName>Referral_Reporting1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outreach_Activity_Type__c</fullName>
        <label>Outreach Activity Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/ReferralReportingDay__mdt.object
<CustomObject>
    <label>ReferralReportingDay</label>
    <pluralLabel>ReferralReportingDay</pluralLabel>
    <fields>
        <fullName>RefReportingDays__c</fullName>
        <label>RefReportingDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

globalValueSets/Community_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>APT</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>BAK</fullName>
    </customValue>
    <customValue>
        <fullName>CAB</fullName>
    </customValue>
    <customValue>
        <fullName>DTT</fullName>
    </customValue>
    <customValue>
        <fullName>EAA</fullName>
    </customValue>
    <customValue>
        <fullName>GDD</fullName>
    </customValue>
    <customValue>
        <fullName>Lutheran Home</fullName>
    </customValue>
    <customValue>
        <fullName>Birdwood</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
        <isActive>false</isActive>
        <label>TEST</label>
    </customValue>
    <masterLabel>Community Picklist</masterLabel>
</GlobalValueSet>

classes/BatchTaskCreateReferralReporting.cls
global class BatchTaskCreateReferralReporting implements Database.Batchable<sObject>, Database.Stateful {
    
    public Date cutoffDate;
   
    public List<ReferralReportingDay__mdt> lstCutOff = new List<ReferralReportingDay__mdt>();

    
    global BatchTaskCreateReferralReporting()  {        
               
        Integer cutoffdateCalculator;

        lstCutOff = [SELECT RefReportingDays__c FROM ReferralReportingDay__mdt];
        cutoffdateCalculator = Integer.valueOf(lstCutOff[0].RefReportingDays__c);

        cutoffDate = Date.Today().addDays(-cutoffdateCalculator);
        system.debug('cutoffDate ' + cutoffDate);

        List<Referral_Reporting__c > lstOADel = [select Id, Metric_Type__c from Referral_Reporting__c where Metric_Type__c = 'Marketing Activity' and Date__c >=: cutoffDate];

        if (lstOADel != null)
            if (lstOADel.size() > 1)
                Delete lstOADel;
        
            
    }    
    global Iterable<sObject> start (Database.BatchableContext bc){
        system.debug('Batch Start');

        String query = 'select Id,WhoId, AccountId, ActivityDate , Activity_Complete_Date__c, Activity_Type__c, Account.Reporting_community__c  FROM Task WHERE IsDeleted = false and Is_Complete__c = TRUE AND Whoid in (SELECT Id From Contact where RecordType.Name = \'Business\') AND System__c = FALSE AND WhoId != NULL AND Account.Reporting_community__c != NULL AND Activity_Complete_Date__c >=: cutoffDate ALL ROWS';
        system.debug('query ' + query);
        return Database.query(query);
    }
    
    // The batch job executes and operates on one batch of records
    
    global void execute(Database.BatchableContext BC, List<Task> scope) {
        system.debug('Inside Execute');
       String contact_prefix = Schema.SObjectType.Contact.getKeyPrefix();
       List<Referral_Reporting__c> lstRR = new List<Referral_Reporting__c>();
       system.debug('Task scope ' + scope);
       Id nullId;
       nullId = NULL;
       
       if (scope!=null)
           if (!scope.isEmpty()){
               
            List<Task> lstTask = new List<Task>();  
            for(Task objtsk: scope)  {
                if(((String)objtsk.WhoId).startsWith(contact_prefix))
                    lstTask.add(objtsk);
            }
            system.debug('lstTask ' +  lstTask);
            for (Task oTask : lstTask)
            {
                Referral_Reporting__c rrobj = new Referral_Reporting__c();
                rrobj.Community__c = oTask.Account.Reporting_community__c; 
                rrobj.Referral_Contact__c = oTask.WhoId;
                rrobj.Date__c = oTask.Activity_Complete_Date__c;
             //   rrobj.Referral_Type__c = '';
                rrobj.Metric_Type__c = 'Marketing Activity';
                rrobj.Outreach_Activity_Type__c = oTask.Activity_Type__c;
                
                rrobj.Patient_Contact__c = nullId;
                lstRR.add(rrobj);
            }   
            system.debug('lstRR ' +  lstRR);            
            if(lstRR.size()>0)
                insert lstRR;
           }
        
        
        
    }
    
    global void finish(Database.BatchableContext BC) {
    
     BatchEventCreateReferralReporting b=new BatchEventCreateReferralReporting();
     Database.executeBatch(b);
     
    }
}