objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Organization_Code__c</fullName>
        <label>Referral Organization Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ref_Org_Code__c</fullName>
        <label>Ref Org Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/Community_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>APT</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>BAK</fullName>
    </customValue>
    <customValue>
        <fullName>CAB</fullName>
    </customValue>
    <customValue>
        <fullName>DTT</fullName>
    </customValue>
    <customValue>
        <fullName>EAA</fullName>
    </customValue>
    <customValue>
        <fullName>GDD</fullName>
    </customValue>
    <customValue>
        <fullName>Lutheran Home</fullName>
    </customValue>
    <customValue>
        <fullName>Birdwood</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
        <isActive>false</isActive>
        <label>TEST</label>
    </customValue>
    <masterLabel>Community Picklist</masterLabel>
</GlobalValueSet>

classes/trigLeadRefOrgTest.cls
@isTest
private class trigLeadRefOrgTest {

    @isTest
    static void Test1(){
    
        Account a1 = new Account(Referral_Organization_Code__c = 'APFM', Community__c = 'Lutheran Home', Name = 'APFM');
        insert a1;
        Lead ld1 = new Lead(FirstName = 'F1', LastName = 'L1', Company = 'CompanyA', LeadSource = 'OL - Online Directory', 
        Ref_Org_Code__c = 'APFM', Community__c = 'Lutheran Home');
        
        Test.startTest();
        insert ld1;
        Test.stopTest();
        
    }
    
    @isTest
    static void Test2(){
    
      //  Account a1 = new Account(Referral_Organization_Code__c = 'APFM', Community__c = 'Lutheran Home', Name = 'APFM');
      //  insert a1;
        Lead ld1 = new Lead(FirstName = 'F1', LastName = 'L1', Company = 'CompanyA', LeadSource = 'OL - Online Directory',  
        Ref_Org_Code__c = 'APFM', Community__c = 'Lutheran Home');
        
        Test.startTest();
        insert ld1;
        Test.stopTest();
        
    }
}