objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Navihealth_Id__c</fullName>
        <label>Navihealth Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The most recent message containing the XML payload used to create or update this lead</description>
        <label>Message</label>
        <referenceTo>Message__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Message__c.object
<CustomObject>
    <description>Logs for Allscripts leads</description>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>true</defaultValue>
        <description>True if the lead was created or updated successfully</description>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Body_XML__c</fullName>
        <description>XML payload that was used to create the lead from Allscripts</description>
        <label>Body XML</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>Response from the API</description>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

globalValueSets/Community_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>APT</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>BAK</fullName>
    </customValue>
    <customValue>
        <fullName>CAB</fullName>
    </customValue>
    <customValue>
        <fullName>DTT</fullName>
    </customValue>
    <customValue>
        <fullName>EAA</fullName>
    </customValue>
    <customValue>
        <fullName>GDD</fullName>
    </customValue>
    <customValue>
        <fullName>Lutheran Home</fullName>
    </customValue>
    <customValue>
        <fullName>Birdwood</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
        <isActive>false</isActive>
        <label>TEST</label>
    </customValue>
    <masterLabel>Community Picklist</masterLabel>
</GlobalValueSet>

classes/NavihealthApi.cls
// POST for message and GET for community
@RestResource(urlMapping='/Navihealth/*')
global with sharing class NavihealthApi {
	@httpPost
    global static Integer setMessage(String leadId, String hl7Body, Integer status, String response) {
        Message__c message = new Message__c();
        message.Source__c = 'Navihealth';
        
        // Find the newly created lead
        if (String.isNotBlank(leadId)){
            Lead lead = [SELECT Id FROM Lead WHERE Id=:leadId];
            if (lead != null)
                message.Lead__c = lead.Id;
        }
   		
        if (String.isNotBlank(hl7Body))
			message.Body_XML__c = hl7Body;
        
        if (status == 200 || status == 204){
            message.Success__c = true;
        } else {
            message.Success__c = false;
        }
        
        message.Response__c = response;
        
        try {
            insert message;
            return 200;
        } catch (DmlException e){
            System.debug(e.getMessage());
            return 400;
        }
    }
    
    @httpGet
    global static String getCommunityName(){
        RestRequest req = RestContext.request;
        String externalId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        list<community__c> comms = [SELECT Id, Name FROM Community__c WHERE Navihealth_Id__c=:externalId];
        if (comms.size() > 0)
            return comms[0].Name;
        else
        	return '';
    }
}