objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Family Member/Influencer/Household Member of Prospect</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Resident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Resident</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Resident)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Community</label>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Inquiry_Date__c</fullName>
        <label>Inquiry Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Referral_Reporting__c.object
<CustomObject>
    <label>Referral Reporting</label>
    <nameField>
        <displayFormat>RR-{0}</displayFormat>
        <label>Referral Reporting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Reporting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Referral Reporting</relationshipLabel>
        <relationshipName>Referral_Reporting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Metric_Type__c</fullName>
        <label>Metric Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing Activity</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Admit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referral Reporting</relationshipLabel>
        <relationshipName>Referral_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referral Reporting (Referral Contact)</relationshipLabel>
        <relationshipName>Referral_Reporting1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Referral</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Referral Reporting</relationshipLabel>
        <relationshipName>Referral_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outreach_Activity_Type__c</fullName>
        <label>Outreach Activity Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/ReferralReportingDay__mdt.object
<CustomObject>
    <label>ReferralReportingDay</label>
    <pluralLabel>ReferralReportingDay</pluralLabel>
    <fields>
        <fullName>RefReportingDays__c</fullName>
        <label>RefReportingDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

globalValueSets/Community_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ALB</fullName>
    </customValue>
    <customValue>
        <fullName>APT</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>BAK</fullName>
    </customValue>
    <customValue>
        <fullName>CAB</fullName>
    </customValue>
    <customValue>
        <fullName>DTT</fullName>
    </customValue>
    <customValue>
        <fullName>EAA</fullName>
    </customValue>
    <customValue>
        <fullName>GDD</fullName>
    </customValue>
    <customValue>
        <fullName>Lutheran Home</fullName>
    </customValue>
    <customValue>
        <fullName>Birdwood</fullName>
    </customValue>
    <customValue>
        <fullName>TEST</fullName>
        <isActive>false</isActive>
        <label>TEST</label>
    </customValue>
    <masterLabel>Community Picklist</masterLabel>
</GlobalValueSet>

classes/BatchOppCreateReferralReporting.cls
/*
Creates Referral Report records representing Referrals and Admits for each Referral Contact/Opportunity (referred by) Combination
When complete calls BatchTaskCreateReferralReporting, which creates Referral Reporting records for each outreach Task, and
which, in turn, calls BatchEventCreateReferralReporting, which creates Referral Reporting records for each outreach Event

As a first step, each batch (first 2) deletes referral reporting records going back X days, after which they are recomputed for that time period
Initial run should cover last full reporting period, e.g. last 12 months.  After initial run, the days should be pulled back to recent, e.g. 60 days

We dont use Referral Type because we only process one referral contact field, the HC Referring Practioner
*/
global class BatchOppCreateReferralReporting implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    
    public Date cutoffDate;
   
    public List<ReferralReportingDay__mdt> lstCutOff = new List<ReferralReportingDay__mdt>();

    global BatchOppCreateReferralReporting()  {        
               
        Integer cutoffdateCalculator;

        lstCutOff = [SELECT RefReportingDays__c FROM ReferralReportingDay__mdt];
        cutoffdateCalculator = Integer.valueOf(lstCutOff[0].RefReportingDays__c);
        system.debug('cutoffdateCalculator ' + cutoffdateCalculator );
        cutoffDate = Date.Today().addDays(-cutoffdateCalculator);
        system.debug('cutoffDate ' + cutoffDate);

        List<Referral_Reporting__c > lstOADel = [select Id, Metric_Type__c from Referral_Reporting__c where
           (Metric_Type__c = 'Referral' OR Metric_Type__c = 'Admit') and Date__c >=: cutoffDate];
        system.debug('lstOADel ' + lstOADel );
        if (lstOADel != null)
            if (lstOADel.size() > 1)
                Delete lstOADel;
        
            
    }    
    global Iterable<sObject> start (Database.BatchableContext bc){
        system.debug('Batch Start');

        String query = 'select Id, HealthCloudGA__ReferringPractitioner__c, Opportunity_Inquiry_Date__c, Primary_Resident__c, Reporting_Community__c, Move_In_Date__c FROM Opportunity where HealthCloudGA__ReferringPractitioner__c != NULL AND Opportunity_Inquiry_Date__c >=: cutoffDate AND Reporting_Community__c != NULL';

        
        return Database.query(query);
    }
    
    // The batch job executes and operates on one batch of records
    
    global void execute(Database.BatchableContext BC, List<Opportunity> scope) {
        system.debug('Inside Execute');
       //String contact_prefix = Schema.SObjectType.Contact.getKeyPrefix();
       List<Referral_Reporting__c> lstRR = new List<Referral_Reporting__c>();
       system.debug('Opportunity scope ' + scope);
       
       if (scope!=null)
           if (!scope.isEmpty()){
               
            List<Opportunity> lstOpportunity = new List<Opportunity>();  
            for(Opportunity objOpp: scope)  {
                //if(((String)objtsk.WhoId).startsWith(contact_prefix))
                    lstOpportunity.add(objOpp);
            }
            system.debug('lstOpportunity ' +  lstOpportunity);
            for (Opportunity oOpportunity : lstOpportunity)
            {

                system.debug('oOpportunity.HealthCloudGA__ReferringPractitioner__c' + oOpportunity.HealthCloudGA__ReferringPractitioner__c);
         
                if(oOpportunity.HealthCloudGA__ReferringPractitioner__c != NULL) {
                    system.debug('referral contact');
                    Referral_Reporting__c rrobj = new Referral_Reporting__c();
                    rrobj.Community__c = oOpportunity.Reporting_Community__c;
                    rrobj.Referral_Contact__c = oOpportunity.HealthCloudGA__ReferringPractitioner__c;
                    // rrobj.Referral_Type__c = 'Referral Contact';
                    rrobj.Date__c = oOpportunity.Opportunity_Inquiry_Date__c;
                    rrobj.Related_Referral__c = oOpportunity.Id;
                    rrobj.Metric_Type__c = 'Referral';
                    rrobj.Outreach_Activity_Type__c = NULL;
                    rrobj.Patient_Contact__c = oOpportunity.Primary_Resident__c;
                    lstRR.add(rrobj);  
                    //create a second Referral_Reporting__c record when Opportunity Move In Date is not blank
                    if(oOpportunity.Move_In_Date__c != NULL)       {
                        
                        Referral_Reporting__c rrobj1 = new Referral_Reporting__c();
                        rrobj1.Community__c = oOpportunity.Reporting_Community__c;
                        rrobj1.Referral_Contact__c = oOpportunity.HealthCloudGA__ReferringPractitioner__c;
                      //  rrobj1.Referral_Type__c = 'Referral Contact';
                        rrobj1.Date__c = oOpportunity.Move_In_Date__c;
                        rrobj1.Related_Referral__c = oOpportunity.Id;
                        rrobj1.Metric_Type__c = 'Admit';
                        rrobj1.Outreach_Activity_Type__c = NULL;
                        rrobj1.Patient_Contact__c = oOpportunity.Primary_Resident__c;
                        lstRR.add(rrobj1);
                    }                   
                }
                
            }   
            system.debug('lstRR ' +  lstRR);            
            if(lstRR.size()>0)
                insert lstRR;
           }
        
    }
    
    global void finish(Database.BatchableContext BC) {
         BatchTaskCreateReferralReporting b=new BatchTaskCreateReferralReporting();
     Database.executeBatch(b);
     
    }
    
     public void execute(SchedulableContext SC){
        BatchOppCreateReferralReporting oBatchOppCreateReferralReporting  = new BatchOppCreateReferralReporting(); 
        Database.executeBatch(oBatchOppCreateReferralReporting , 100);
    }
}