objects/Disable_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Disable Trigger</label>
    <fields>
        <fullName>Trigger_Disabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Trigger Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_For_Users__c</fullName>
        <label>Disable For Users</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

classes/DisableTrigger.cls
global class DisableTrigger {
    global static boolean isDisabled(string strName){
        try{
            Disable_Trigger__c objDisableTrigger = Disable_Trigger__c.getInstance(strName);
            if (objDisableTrigger!=null) if (objDisableTrigger.Trigger_Disabled__c){
                if (objDisableTrigger.Disable_For_Users__c!=null) 
                    if (string.valueOf(objDisableTrigger.Disable_For_Users__c).trim()!='')
                        return (string.valueOf(objDisableTrigger.Disable_For_Users__c).containsIgnoreCase(UserInfo.getUserName()));
                return true;
            }
            return false;
        }
        catch(Exception exc){return false;}
    }
}