objects/External_Submission_Error__c.object
<CustomObject>
    <label>External Submission Error</label>
    <nameField>
        <label>External Submission Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Submission Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/apfmRefService.cls
@RestResource(urlMapping='/apfmReferral')
global without sharing class apfmRefService {
    @HttpPost
    global static String doPost(){
      String submissionString = null;
      try {
        string strInterfaceName = 'APFM';
        String resp;
        RestRequest req = RestContext.request;
        String referral = req.requestBody.toString();
        submissionString = referral;

        if(referral != null) if (referral.trim() != ''){
            TLGJsonInterface.Submit(strInterfaceName, referral);
        }
        resp = 'Complete';
        return resp;
        } catch (Exception e) {
           External_Submission_Error__c ese = new External_Submission_Error__c(Submission__c = submissionString,Error__c = e.getMessage(),Source__c = 'APFM');
           insert ese; return e.getMessage();
        }
    }
}