objects/Lead.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Inquiry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Inquiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prospect_Last_Name__c</fullName>
        <label>Prospect Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Source Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Activity_Type__c</fullName>
        <label>Initial Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Call In</fullName>
                </value>
                <value>
                    <fullName>Initial Email In</fullName>
                </value>
                <value>
                    <fullName>Initial Mail In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In Appointment</fullName>
                </value>
                <value>
                    <fullName>Initial Call Out</fullName>
                </value>
                <value>
                    <fullName>Initial Email Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Addl_Prospect_Last_Name__c</fullName>
        <label>Addl Prospect Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Activity_Date__c</fullName>
        <label>Follow Up Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Activity_Type__c</fullName>
        <label>Follow Up Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Call In</fullName>
                </value>
                <value>
                    <fullName>Call Out</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Closing Appointment</fullName>
                </value>
                <value>
                    <fullName>Community Experience</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>Email In</fullName>
                </value>
                <value>
                    <fullName>Email Out</fullName>
                </value>
                <value>
                    <fullName>Home Visit</fullName>
                </value>
                <value>
                    <fullName>Initial Appointment</fullName>
                </value>
                <value>
                    <fullName>Initial Call In</fullName>
                </value>
                <value>
                    <fullName>Initial Email In</fullName>
                </value>
                <value>
                    <fullName>Initial Mail In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In</fullName>
                </value>
                <value>
                    <fullName>Initial Walk In Appointment</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Mail In</fullName>
                </value>
                <value>
                    <fullName>Mail Out - Personal Mail</fullName>
                </value>
                <value>
                    <fullName>Move In</fullName>
                </value>
                <value>
                    <fullName>Move Out</fullName>
                </value>
                <value>
                    <fullName>Post-Deposit Appointment</fullName>
                </value>
                <value>
                    <fullName>Resident Appointment</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_to_Prospect__c</fullName>
        <label>Relationship to Prospect</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Relationship_to_Prospect</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Not_Opened_After_Conversion_Yet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Not Opened After Conversion Yet</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Senior_Living</fullName>
        <active>true</active>
        <businessProcess>Senior Living</businessProcess>
        <label>Senior Living</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Lead_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_Opened_After_Conversion_Yet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Not Opened After Conversion Yet</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Senior_Living</fullName>
        <active>true</active>
        <businessProcess>SP Senior Living</businessProcess>
        <label>Senior Living</label>
    </recordTypes>
</CustomObject>

globalValueSets/Relationship_to_Prospect.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Self</fullName>
    </customValue>
    <customValue>
        <fullName>Friend</fullName>
    </customValue>
    <customValue>
        <fullName>Spouse</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Son</fullName>
    </customValue>
    <customValue>
        <fullName>Daughter</fullName>
    </customValue>
    <customValue>
        <fullName>Sister</fullName>
    </customValue>
    <customValue>
        <fullName>Brother</fullName>
    </customValue>
    <customValue>
        <fullName>Father</fullName>
    </customValue>
    <customValue>
        <fullName>Mother</fullName>
    </customValue>
    <customValue>
        <fullName>Other Relative</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Guardian</fullName>
    </customValue>
    <masterLabel>Relationship to Prospect</masterLabel>
</GlobalValueSet>

classes/refreshContactControllerTest.cls
/* Test class for refreshContactController
 *
 * @author Lansdale Group
 * @since Dec 06 2021

 */

@isTest
public class refreshContactControllerTest {

    public static testMethod void  refreshContactControllerTest   () {
   
        Campaign  c = new Campaign(IsActive = true, Name = 'Test');
        insert c;
   
        Lead ld = new Lead();
        ld.FirstName = 'Test';
        ld.LastName = 'Test';
 //       ld.Company = 'Test Test';
        ld.Relationship_to_Prospect__c = 'Self';
        ld.Lead_Source_Campaign__c = c.id;
        ld.Follow_Up_Activity_Type__c = 'Call Out';
        ld.Follow_Up_Activity_Date__c = Date.today();
        ld.Initial_Activity_Type__c = 'Call Out';
        ld.LeadSource = 'Other';
        ld.Prospect_Last_Name__c = 'Test3';
        ld.Addl_Prospect_Last_Name__c = 'Test2';
        //ld.Addl_Relationship_to_Prospect__c  = 'Spouse';
        ld.Inquiry_Date__c = Date.TODAY();
        List<RecordType> lstId = [SELECT Id FROM RecordType where DeveloperName = 'Senior_Living' AND SObjectType = 'Lead'];
        Id rectypeid;
    if (lstId  != null)
      for (RecordType i: lstId)
         if (i.Id != null)
            rectypeid= i.Id;
            
        insert ld;
       
        List<Id> lstIds = new List<Id>();
        lstIds.add(ld.Id);
       
        AutoConvertLeads.LeadAssign(lstIds );
// everything up to here is just the original autoconvertleadstest

        Lead l1;
        for (Lead l: [ select ConvertedAccountId   from Lead where Id in :lstIds ])
           l1 = l;
           List<Opportunity> lstOpp = [select Not_Opened_After_Conversion_Yet__c  from Opportunity];
         for (Opportunity o: lstOpp )
            o.Not_Opened_After_Conversion_Yet__c   = true;
          update lstOpp; 
         refreshContactController.getOpportunity(l1.ConvertedAccountId  );
    }
}