objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Housing_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Inquiry_Date__c</fullName>
        <label>Inquiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Toggle_Create_System_Activities_Trigger__c</fullName>
        <label>Toggle Create System Activities Trigger</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Senior_Living</fullName>
        <active>true</active>
        <businessProcess>SP Senior Living</businessProcess>
        <label>Senior Living</label>
    </recordTypes>
</CustomObject>

globalValueSets/Housing_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Assisted Living</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Living</fullName>
        <default>true</default>
        <label>Independent Living</label>
    </customValue>
    <customValue>
        <fullName>Residential Living</fullName>
    </customValue>
    <customValue>
        <fullName>Assisted Living Respite</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Day Club</fullName>
    </customValue>
    <customValue>
        <fullName>Assisted Living Memory Support</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Respite</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Rehab</fullName>
    </customValue>
    <customValue>
        <fullName>Memory Support</fullName>
    </customValue>
    <customValue>
        <fullName>Hospice</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>Skilled Nursing</fullName>
    </customValue>
    <customValue>
        <fullName>Community Events</fullName>
        <isActive>false</isActive>
        <label>Community Events</label>
    </customValue>
    <customValue>
        <fullName>Memory Care</fullName>
        <isActive>false</isActive>
        <label>Memory Care</label>
    </customValue>
    <masterLabel>Housing Type</masterLabel>
</GlobalValueSet>

classes/OppSystemActivityHelperTest.cls
@isTest
public class OppSystemActivityHelperTest {
  @isTest
    static void myUnitTest01() {
        Account acc = new Account();
        acc.Name = 'TEST';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Viv Richards';
        opp.AccountId = acc.Id;
        opp.CloseDate = Date.Today();
        opp.StageName = 'Prospecting';
        opp.Opportunity_Inquiry_Date__c= Date.Today().addDays(-3);
        opp.Move_In_Date__c = Date.Today().addDays(-2);
        opp.Toggle_Create_System_Activities_Trigger__c = 'YES';
   
        opp.RecordTypeId  = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Senior_Living').getRecordTypeId();
        opp.Service_Type__c = 'Assisted Living';
        insert opp;

        Test.startTest();
  
        
        opp.Opportunity_Inquiry_Date__c= Date.Today().addDays(-1);
        opp.Move_In_Date__c= Date.Today().addDays(-1);
        opp.Toggle_Create_System_Activities_Trigger__c = 'NO';
        update opp;
        opp.Move_In_Date__c= null;
        update opp;
        Test.stopTest();
        
    }
}